sudo: false
dist: xenial
language: python
cache: pip

python:
- 3.6
- 3.6-dev

install:
- pip install pipenv
- pipenv install --dev --system
script:
- make flake8
- make stylecheck

notifications:
  on_success: never
  on_failure: never
