"""DocRef - Search for references on documentation webpages generated by Sphinx."""
from .docref import DocRef
from .errors import AlreadyUpToDate  # noqa: F401
from .types import NodeRef  # noqa: F401


def setup(bot):
    bot.add_cog(DocRef())
